// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yigafgqqypnzebrdlbgj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpZ2FmZ3FxeXBuemVicmRsYmdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg5OTQ3NTgsImV4cCI6MjA4NDU3MDc1OH0.RyR6wvKM-zovCbQ4jleG_oXULDEa209mjc34yASAPAU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});